policy_repository/configuration/urls.py
from django.conf.urls import url

from . import views

app_name = 'configuration'

urlpatterns = [
    url(r'^$', views.configuration_view, name='configuration'),
    url(r'^update_people/$', views.update_people_view, name='update_people'),
    url(r'^upload_files/$', views.upload_files_to_library_view, name='upload_files'),
    url(r'^add_policy_subtype/$', views.add_policy_subtype_view, name='add_policy_subtype'),
    url(r'^add_municipality_type/$', views.add_muni_type_view, name='add_municipality_type'),

]

policy_repository/policy_repository/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from accounts.views import (login_view, register_view, logout_view)
# from configuration.views import (configuration_view, update_people_view)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^register/', register_view, name='register'),
    url(r'^configuration/', include('configuration.urls')),
    # url(r'^configuration/update_people', update_people_view, name='update_people'),

    url(r'^', include('polrep.urls')),
]

policy_repository/polrep/urls.py
from django.conf.urls import url

from . import views
from django.contrib.auth import views as auth_views

app_name = 'polrep'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^search/$', views.retrieve, name='retrieve'),
    url(r'^pdf_viewer/(?P<pdf_name>[-\w.]+)$', views.pdf_viewer, name='pdf_viewer'),
    url(r'^pdf_download/(?P<pdf_name>[-\w.]+)$', views.pdf_download, name='pdf_download'),
]

policy_repository/polrep/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class Policy(models.Model):
    file_path = models.CharField(max_length=1024)
    # word_count = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.file_path

    def __unicode__(self):
        return self.file_path


class Subtype(models.Model):
    subtype_name = models.CharField(max_length=250)

    def __str__(self):
        return self.subtype_name

    def __unicode__(self):
        return self.subtype_name


class Year(models.Model):
    year = models.CharField(max_length=4)

    def __str__(self):
        return self.year

    def __unicode__(self):
        return self.year


class MunicipalityName(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name


class MunicipalityType(models.Model):
    mtype = models.CharField(max_length=50)

    def __str__(self):
        return self.mtype

    def __unicode__(self):
        return self.mtype


class PolicyStance(models.Model):
    stance = models.CharField(max_length=10)

    def __str__(self):
        return self.stance

    def __unicode__(self):
        return self.stance

policy_repository/polrep/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from models import MunicipalityName, MunicipalityType, Year, Subtype, PolicyStance, Policy

from django.http import HttpResponse
from django.conf import settings

import os


def index(request):
    subtypes = Subtype.objects.all()
    muni_names = MunicipalityName.objects.all()
    muni_types = MunicipalityType.objects.all()
    years = Year.objects.all()
    stances = PolicyStance.objects.all()

    try:
        fn, ln = (request.user.first_name, request.user.last_name)
        username = request.user.username

        current_user = "{0} {1}".format(fn, ln) if len(fn) > 0 and len(ln) > 0 else username

        context = {
            'current_user': current_user,
            'subtypes': subtypes,
            'muni_names': muni_names,
            'muni_types': muni_types,
            'years': years,
            'stances': stances,
        }

    except:
        context = {
            'subtypes': subtypes,
            'muni_names': muni_names,
            'muni_types': muni_types,
            'years': years,
            'stances': stances,
        }

    return render(request, 'polrep/index.html', context)


def fetch_file(active_parameters, f):
    valid_fetch = all(kw in f.file_path.lower().replace('-', ' ').replace('_', ' ') for kw in active_parameters)

    if valid_fetch == True:
        return f
    else:
        return False


def get_active_parameters(parameters):
    return [str(p).lower().replace('\r\n', '') for p in parameters if p is not None]


def retrieve(request):
    query_tag_html = request.POST.get('query-tag-html')

    muni_name = request.POST.get('muni-name-select')
    muni_type = request.POST.get('muni-type-select')
    pol_stance = request.POST.get('pol-stance-select')
    pol_year = request.POST.get('pol-year-select')
    pol_subtype = request.POST.get('pol-subtype-select')

    parameters = get_active_parameters([muni_name, muni_type, pol_stance, pol_year, pol_subtype])

    all_files = Policy.objects.all()

    results = []

    for f in all_files:
        fetched_file = fetch_file(parameters, f)
        if fetched_file is not False:
            results.append(fetched_file)

    subtypes = Subtype.objects.all()
    muni_names = MunicipalityName.objects.all()
    muni_types = MunicipalityType.objects.all()
    years = Year.objects.all()
    stances = PolicyStance.objects.all()

    try:
        fn, ln = (request.user.first_name, request.user.last_name)
        username = request.user.username

        current_user = "{0} {1}".format(fn, ln) if len(fn) > 0 and len(ln) > 0 else username

        context = {
            'query_tags': query_tag_html,
            'results': results,
            'number_of_results': len(results),
            'result_or_results': 'Results' if len(results) > 1 or len(results) == 0 else 'Result',
            'subtypes': subtypes,
            'muni_names': muni_names,
            'muni_types': muni_types,
            'years': years,
            'stances': stances,
            'highlights': parameters,
            'current_user': current_user,
            'subtypes': subtypes,
            'muni_names': muni_names,
            'muni_types': muni_types,
            'years': years,
            'stances': stances,
        }

    except:
        context = {
            'query_tags': query_tag_html,
            'results': results,
            'number_of_results': len(results),
            'result_or_results': 'Results' if len(results) > 1 or len(results) == 0 else 'Result',
            'subtypes': subtypes,
            'muni_names': muni_names,
            'muni_types': muni_types,
            'years': years,
            'stances': stances,
            'highlights': parameters,
            'subtypes': subtypes,
            'muni_names': muni_names,
            'muni_types': muni_types,
            'years': years,
            'stances': stances,
        }

    return render(request, 'polrep/index.html', context)


def pdf_viewer(request, pdf_name):
    pdf_name = pdf_name.replace('-', '/').replace('_', ' ')

    with open(os.path.join(settings.MEDIA_ROOT, pdf_name), 'rb') as pdf:
        response = HttpResponse(pdf.read(), content_type='application/pdf')
        response['Content-Disposition'] = 'inline;filename={0}'.format(pdf_name)
        return response


def pdf_download(request, pdf_name):
    pdf_name = pdf_name.replace('-', '/').replace('_', ' ')

    with open(os.path.join(settings.MEDIA_ROOT, pdf_name), 'rb') as pdf:
        response = HttpResponse(pdf.read(), content_type='application/pdf')
        response['Content-Disposition'] = 'attachment;filename={0}'.format(pdf_name)
        return response

policy_repository/polrep/templates/polrep/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load static %}
    {% load polrep_extras %}

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'polrep/css/style.css' %}">
    <title>PolRep</title>
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'polrep:index' %}">pol<strong>rep</strong></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
            <li><a href="#">Link</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            {% if current_user %}
            <li class="dropdown">
              <a id="user-dropdown" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span> Welcome, <strong>{{ current_user }}</strong> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'configuration:configuration' %}">
                  <span class="glyphicon glyphicon-cog" aria-hidden="true"></span> Configuration
                </a></li>
                <li role="separator" class="divider"></li>
                <li class="text-center"><a id="signout-btn" href="{% url 'logout' %}">
                  <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> Sign Out
                </a></li>
              </ul>
            </li>

            {% else %}

            <li><a id="signin-btn" href="{% url 'login' %}">
              Sign In
              <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
            </a></li>
            <li><a href="{% url 'register' %}">
              Register
            </a></li>
            {% endif %}
          </ul>
        </div> <!-- /.navbar-collapse -->
      </div> <!-- /.container-fluid -->
    </nav>

    <div class="container">
      {% if logout_message %}
      <div class="alert alert-success alert-dismissible text-center" role="alert">
        <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        {{ logout_message }} <a href="{% url 'login' %}">Sign In</a> again?
      </div>

      {% endif %}

      <form id="policy-search-form">
        {% csrf_token %}
        <input type="hidden" id="form-action-url" name="" value="{% url 'polrep:retrieve' %}">

        <div class="panel panel-default">
          <div class="panel-heading">
            <h2 class="panel-title">Search for Policies</h2>
          </div>
          <div class="panel-body">
            {# MUNICIPALITY NAME AND TYPE #}
            <div class="row">
              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                <div class="form-group">
                  <label for="muni-name-select">Municipality Name</label>
                  <select class="form-control" id="muni-name-select" name="muni-name-select" onchange="add_to_query(this, 'qp1');">
                    <option selected="selected" disabled>Choose a Municipality Name</option>

                    {% for muni in muni_names %}
                    <option value="{{ muni.name }}">{{ muni.name }}</option>
                    {% endfor %}

                  </select>
                </div>
              </div>

              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                <div class="form-group">
                  <label for="muni-type-select">Municipality Type</label>
                  <select class="form-control" id="muni-type-select" name="muni-type-select" onchange="add_to_query(this, 'qp2');">
                    <option selected="selected" disabled>Choose a Municipality Type</option>

                    {% for muni in muni_types %}
                    <option value="{{ muni.mtype }}">{{ muni.mtype }}</option>
                    {% endfor %}

                  </select>
                </div>
              </div>
            </div>
            {# END MUNICIPALITY NAME AND TYPE #}

            {# POLICY STANCE AND YEAR #}
            <div class="row">
              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                <div class="form-group">
                  <label for="pol-stance-select">Policy Stance</label>
                  <select class="form-control" id="pol-stance-select" name="pol-stance-select" onchange="add_to_query(this, 'qp3');">
                    <option selected="selected" disabled>Choose a Policy Stance</option>

                    {% for stance in stances %}
                    <option value="{{ stance.stance }}">{{ stance.stance }}</option>
                    {% endfor %}

                  </select>
                </div>
              </div>

              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                <div class="form-group">
                  <label for="pol-year-select">Policy Year</label>
                  <select class="form-control" id="pol-year-select" name="pol-year-select" onchange="add_to_query(this, 'qp4');">
                    <option selected="selected" disabled>Choose a Policy Year</option>

                    {% for year in years %}
                    <option value="{{ year.year }}">{{ year.year }}</option>
                    {% endfor %}

                  </select>
                </div>
              </div>
            </div>
            {# END POLICY STANCE AND YEAR #}

            {# POLICY TYPE AND SUBTYPE #}
            <div class="row">
              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 centered">
                <div class="form-group">
                  <label for="pol-subtype-select">Policy Subtype</label>
                  <select class="form-control" id="pol-subtype-select" name="pol-subtype-select" onchange="add_to_query(this, 'qp6');">
                    <option selected="selected" disabled>Choose a Policy Subtype</option>

                    {% for subtype in subtypes %}
                    <option value="{{ subtype.subtype_name }}">{{ subtype.subtype_name }}</option>
                    {% endfor %}

                  </select>
                </div>
              </div>
            </div>
            {# END POLICY TYPE AND SUBTYPE #}

          </div> {# panel-body #}
          <div class="panel-footer">
            <div id="empty-query-alert" class="alert alert-danger alert-dismissible" role="alert">
              <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              Your query is empty. Please set at least <strong>1</strong> parameter.
            </div>

            <input id="query-tag-html" type="hidden" name="query-tag-html" value="">

            <input type="button" id="qform-submit-btn" class="btn btn-primary pull-right" name="" value="Search" onclick="check_eq_or_submit();">
            <strong>Query: </strong>

            <span id="full-query">
              <span id="qp1" class="label label-default"></span>
              <span id="qp2" class="label label-primary"></span>
              <span id="qp3" class="label label-success"></span>
              <span id="qp4" class="label label-info"></span>
              <span id="qp5" class="label label-warning"></span>
              <span id="qp6" class="label label-danger"></span>
            </span>

            <div class="clearfix"></div>
          </div>
        </div>
      </form>
    </div>


    <div class="container">
      {% if results %}
      <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading"><h4>Showing <strong>{{ number_of_results }}</strong> {{ result_or_results }} for {{ query_tags|safe }} </h4></div>

        {% if results|length >= 1 %}
        <!-- Table -->
        <div class="panel-body">
          <table class="table table-striped table-hover results">
            {% for result in results %}
              <tr>
                <td class="text-center">{{ forloop.counter }}</td>
                <td>{{ result.file_path|beautify|highlight:highlights|safe }}</td>
                <td class="text-center"><a href="{% url 'polrep:pdf_viewer' pdf_name=result.file_path %}" class="btn btn-default">
                  View
                </a></td>
                <td class="text-center"><a href="{% url 'polrep:pdf_download' pdf_name=result.file_path %}" class="btn btn-primary">
                  Download
                  <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
                </a></td>
              </tr>
            {% endfor %}
          </table>
        </div>

        {% endif %}
      </div>
      {% endif %}

      {% if number_of_results == 0 %}

      <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading"><h4>Showing <strong>{{ number_of_results }}</strong> {{ result_or_results }} for {{ query_tags|safe }} </h4></div>

        <div class="panel-body text-muted text-center">
          <h1>Your query did not yield any results. Please try again!</h1>
        </div>

      </div>
      {% endif %}

    </div>

    <a id="return-to-top"><span class="glyphicon glyphicon-menu-up" aria-hidden="true"></span></a>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <!-- Local JS for additional functionality -->

    <script type="text/javascript" src="{% static 'polrep/js/main.js' %}"></script>

  </body>
</html>

policy_repository/polrep/templates/polrep/register.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load static %}
    {% load polrep_extras %}

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'polrep/css/style.css' %}">
    <title>PolRep</title>
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'polrep:index' %}">pol<strong>rep</strong></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
            <li><a href="#">Link</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li><a id="signin-btn" data-toggle="modal" data-target="#sign-in-modal">
              Sign In
              <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
            </a></li>
            <li><a href="{% url 'polrep:register' %}">
              Register
            </a></li>
          </ul>
        </div> <!-- /.navbar-collapse -->
      </div> <!-- /.container-fluid -->
    </nav>

    <div class="container">

      <form id="registration-form">
        {% csrf_token %}
        <input type="hidden" id="registration-form-action-url" value="{% url 'polrep:register_success'%}">
        <div class="row">
          <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 col-lg-offset-2 col-md-offset-2">
            <div class="form-group">
              <label for="first-name">First Name</label>
              <input type="text" class="form-control form-control-lg" id="first-name" name="first-name" placeholder="Jane" required>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 col-lg-offset-2 col-md-offset-2">
            <div class="form-group">
              <label for="last-name">Last Name</label>
              <input type="text" class="form-control form-control-lg" id="last-name" name="last-name" placeholder="Doe" required>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 col-lg-offset-2 col-md-offset-2">
            <div class="form-group">
              <label for="email">Email</label>
              <input type="email" class="form-control form-control-lg" id="email" name="email" placeholder="e.g. user@example.com" required>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 col-lg-offset-2 col-md-offset-2">
            <div class="form-group">
              <label for="email-repeat">Repeat Email</label>
              <input type="email" class="form-control form-control-lg" id="email-repeat" placeholder="" required>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 col-lg-offset-2 col-md-offset-2">
            <div class="form-group">
              <label for="password">Password</label>
              <input type="password" class="form-control form-control-lg" id="password" name="password" placeholder="e.g. aBc1Zc" required>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 col-lg-offset-2 col-md-offset-2">
            <div class="form-group">
              <label for="password-repeat">Repeat Password</label>
              <input type="password" class="form-control form-control-lg" id="password-repeat" placeholder="" required><br>
              <dl class="text-muted text-center">
                <dt>Your password must contain at least:</dt>
                <dd id="min-chars">6 characters</dd>
                <dd id="min-lc">1 lowecase letter</dd>
                <dd id="min-uc">1 uppercase letter</dd>
                <dd id="min-num">1 number</dd>
              </dl>
            </div>
          </div>

        </div>
        <hr>
        <div class="row text-center">
          <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 col-lg-offset-2 col-md-offset-2">
            <input type="submit" class="btn btn-success btn-lg" id="signup-btn" value="Sign Up">
          </div>
        </div>
      </form>
    </div>

    <a id="return-to-top"><span class="glyphicon glyphicon-menu-up" aria-hidden="true"></span></a>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </body>
</html>